FROM centos:7

RUN yum -y install httpd epel-release yum-utils \
  http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
  yum-config-manager --enable remi-php73 && \
  yum -y install php \
  php-common \
  php-opcache \
  php-mcrypt \
  php-cli \
  php-gd \
  php-curl \
  php-mysqlnd

COPY . /var/www/html

CMD apachectl -DFOREGROUND
